/* Generated by tools/pack_assets.py -- do not edit. Offsets into the
 * packed RetroNET file RICK.DAT in 4-byte units: load with
 * sys_nabu_loadRes(RES_xx, dest, size), byte offset = RES_xx << 2.
 * RICK.SPR (ECM sprite pages) needs no table: byte offset = slot * 384. */
#ifndef _RES_H
#define _RES_H

#define RES_SF18PAT        0x0000  /* SF18PAT.DAT: F18A title pattern */
#define RES_SF18COL        0x0600  /* SF18COL.DAT: F18A title colour */
#define RES_SPLSHPAT       0x0C00  /* SPLSHPAT.DAT: TMS9918A title pattern */
#define RES_SPLSHCOL       0x1200  /* SPLSHCOL.DAT: TMS9918A title colour */
#define RES_MUSIC1         0x1800  /* MUSIC1.DAT: title music */
#define RES_TF18PATA       0x1A0F  /* TF18PATA.DAT: F18A font pattern */
#define RES_TF18COLA       0x1C0F  /* TF18COLA.DAT: F18A font colour */
#define RES_TILECOLA       0x1E0F  /* TILECOLA.DAT: TMS9918A font colour */
#define RES_TILEPATA       0x200F  /* TILEPATA.DAT: TMS9918A font pattern */
#define RES_SPR0           0x220F  /* SPR0.DAT: TMS9918A page-0 sprites */
#define RES_MAPEFLG        0x280F  /* MAPEFLG.DAT: map_eflg_c */
#define RES_ENTDATA        0x2817  /* ENTDATA.DAT: ent_entdata */
#define RES_SPRSEQ         0x291A  /* SPRSEQ.DAT: ent_sprseq */
#define RES_MVSTEP         0x295E  /* MVSTEP.DAT: ent_mvstep */
#define RES_JUMP           0x2AE6  /* JUMP.DAT: sfx */
#define RES_BULLET         0x2AF9  /* BULLET.DAT: sfx */
#define RES_EXPLODE        0x2B0E  /* EXPLODE.DAT: sfx */
#define RES_WALK           0x2B26  /* WALK.DAT: WALK/CRAWL sfx */
#define RES_STICK          0x2B2F  /* STICK.DAT: sfx */
#define RES_BOX            0x2B3A  /* BOX.DAT: sfx */
#define RES_SBONUS         0x2B60  /* SBONUS.DAT: sfx */
#define RES_PAD            0x2B78  /* PAD.DAT: sfx */
#define RES_TREASURE       0x2B99  /* TREASURE.DAT: sfx */
#define RES_DIE            0x2BD6  /* DIE.DAT: sfx */
#define RES_SBONUS2        0x2C46  /* SBONUS2.DAT: sfx */
#define RES_GAMEOVER       0x2C68  /* GAMEOVER.DAT: sfx */
#define RES_BOMBSHHT       0x2C95  /* BOMBSHHT.DAT: fuse sfx */
#define RES_WAAAAA         0x2C9E  /* WAAAAA.PCM: cheat-key PCM */
#define RES_HAFPAT         0x3496  /* HAFPAT.DAT: hall of fame banner pattern */
#define RES_HAFCOL         0x3556  /* HAFCOL.DAT: hall of fame banner colour */

#define RES_MAPSUB_BASE    0x3616  /* MAPSUB1.DAT..MAPSUB4.DAT: per-map submaps */
#define RES_MAPSUB_STRIDE  0x0024
#define RES_MAPCONN_BASE    0x36A6  /* MAPCONN1.DAT..MAPCONN4.DAT: per-map connections */
#define RES_MAPCONN_STRIDE  0x0084
#define RES_MAPBNUM_BASE    0x38B6  /* MAPBNUM1.DAT..MAPBNUM4.DAT: per-map block numbers */
#define RES_MAPBNUM_STRIDE  0x028B
#define RES_MAPMARK_BASE    0x42E2  /* MAPMARK1.DAT..MAPMARK4.DAT: per-map marks */
#define RES_MAPMARK_STRIDE  0x01B3
#define RES_MAPBLK_BASE    0x49AE  /* MAPBLK1.DAT..MAPBLK4.DAT: per-map blocks */
#define RES_MAPBLK_STRIDE  0x0124
#define RES_SPXNUM_BASE    0x4E3E  /* SPXNUM1.DAT..SPXNUM4.DAT: per-map extra sprite numbers */
#define RES_SPXNUM_STRIDE  0x0016
#define RES_TF18SP_BASE    0x4E96  /* TF18SP1.DAT..TF18SP4.DAT: per-map F18A tile set */
#define RES_TF18SP_STRIDE  0x028F
#define RES_TILESP_BASE    0x58D2  /* TILESP1.DAT..TILESP4.DAT: per-map TMS9918A tile set */
#define RES_TILESP_STRIDE  0x028F
#define RES_SPXPAT_BASE    0x630E  /* SPXPAT1.DAT..SPXPAT4.DAT: per-map TMS9918A extra sprites */
#define RES_SPXPAT_STRIDE  0x0580
#define RES_MAPTIT_BASE    0x790E  /* MAPTIT1.DAT..MAPTIT5.DAT: per-intro title text */
#define RES_MAPTIT_STRIDE  0x0008
#define RES_MAPBOD_BASE    0x7936  /* MAPBOD1.DAT..MAPBOD5.DAT: per-intro body text */
#define RES_MAPBOD_STRIDE  0x0047
#define RES_INTRMUS_BASE    0x7A99  /* INTRMUS1.DAT..INTRMUS5.DAT: per-intro music */
#define RES_INTRMUS_STRIDE  0x0268
#define RES_ENT_BASE    0x86A1  /* ENT0.DAT..ENT8.DAT: per-enemy-type kill sfx */
#define RES_ENT_STRIDE  0x0187

#define RES_DAT_LAST       0x945F  /* RICK.DAT's last 4 bytes */
#define RES_SPR_LAST       0x4FDF  /* RICK.SPR's last 4 bytes */

#endif
