/*
 * hal/sys_nabu_load.h
 *
 * Runtime asset loading over RetroNET, for data that used to be compiled
 * straight into the .nabu image as `const` initializers (dat_tilescTI.c's
 * tiles_banks_col[], etc).
 *
 * WHY THIS EXISTS: the TI-99 build pages assets in and out via cartridge
 * bank switching, so its dat_*.c files can all be compiled in at once --
 * whichever bank isn't currently needed just isn't paged in. NABU has no
 * such thing: the whole .nabu image is one flat blob the boot loader reads
 * into RAM in one shot, and everything in it -- code, NABU-LIB, every
 * dat_*.c table -- has to fit under the ~60KB that leaves free of the
 * 64KB address space (the rest is display/sprite buffers, the stack, and
 * headroom for the runtime data these very assets get loaded into). A
 * handful of `const` tables is fine; the pictures, music and map data
 * would not be.
 *
 * The fix: declare the asset arrays as plain (non-const, no initializer)
 * buffers -- see dat_tilescTI.c/dat_tilespTI.c/dat_spritesTI0.c -- so they
 * cost 0 bytes in the image (BSS, not data), and fill them in at startup
 * from files on the Internet Adapter's RetroNET file store via
 * sys_nabu_loadAsset() below. This is really just reverting to the
 * *original* PC xrick's own design -- see engine/include/sprites.h's "PC
 * version" comment block: "Sprites are stored in 'sprites.bin' and are
 * loaded by spr_init." -- which the TI port moved away from only because
 * it had banking to spend instead.
 *
 * The corresponding .DAT files this loads live in assets/ in this
 * repo (see that folder's README) and need to be copied into the Internet
 * Adapter's configured RetroNET Store folder before the game will run --
 * sys_nabu_checkFiles() below stops at boot with a message if they're
 * missing or out of date.
 *
 * PRECONDITION: like every rn_* call in hal/RetroNET-FileStore.h, this
 * requires an Internet Adapter to actually be attached over HCCA. Neither
 * that file nor this one can detect its absence ahead of time -- there's
 * no "is RetroNET there" query, just the read itself -- so calling this
 * with no IA connected will hang inside rn_FileRead()'s byte-wait loop
 * rather than fail cleanly. Nothing to do about that until NABU-LIB grows
 * a presence check; document it here instead of pretending it can't
 * happen.
 */

#ifndef _SYS_NABU_LOAD_H
#define _SYS_NABU_LOAD_H

#include "ricksystem.h"
#include "res.h" /* RES_xx offsets, generated by tools/pack_assets.py */

/*
 * PACKED ASSETS: every asset lives in one of two RetroNET files, built by
 * tools/pack_assets.py (build.ps1 runs it before every compile) from the
 * individual source files in assets/:
 *
 *   RICK.DAT -- everything except ECM sprites. Addressed by the RES_xx
 *               constants in engine/include/res.h (4-byte units).
 *   RICK.SPR -- the five interleaved ECM sprite pages; byte offset =
 *               physical slot * SPRITE_PLANES_SIZE.
 *
 * Same number of network reads as the old one-file-per-asset layout --
 * every read just names a different file and an offset instead. The
 * "RICK." part of the name is fixed in sys_nabu_load.c's path; callers
 * pass just the extension. Names are uppercase on purpose: nabu.ca
 * uppercases uploaded files, and a case-sensitive server would not match
 * a lowercase request.
 */
#define RES_FILE "DAT"
#define SPRITE_FILE "SPR"

/* Reads `size` bytes of file RICK.<ext> (ext = RES_FILE or SPRITE_FILE)
 * into `dest`, starting `at4` * 4 bytes in.
 * Offsets are in 4-byte units so they fit 16 bits for both packed files
 * (every entry in RICK.DAT is 4-byte aligned, and every read the game makes
 * inside one -- 128/384-byte sprite frames, 512-byte title chunks -- is a
 * multiple of 4), keeping 32-bit math out of every caller. */
/* Returns the bytes read. If the adapter doesn't answer at all within a
 * few seconds, shows "CPM/N/1/RICK.xxx NO RETRONET REPLY" and stops (see
 * sys_nabu_checkFiles()). */
U16 sys_nabu_loadAssetOffset(const char *ext, U8 *dest, U16 at4, U16 size);

/* Reads `size` bytes of resource `res` (a RES_xx constant, or a RES_x_BASE
 * + index * RES_x_STRIDE group member) from RICK.DAT into `dest`. RES_ values
 * are already in 4-byte units, so part of one is RES_xx + byteOffset / 4. */
void sys_nabu_loadRes(U16 res, U8 *dest, U16 size);

/* Boot check: reads the last 4 bytes of RICK.DAT and RICK.SPR. If either
 * can't be read (missing, or shorter than this build expects -- i.e. out of
 * date), shows "CPM/N/1/RICK.xxx NOT FOUND OR OLD" on screen and stops;
 * if the adapter doesn't answer at all within a few seconds, "NO
 * RETRONET REPLY".
 * Call after initNABULib() and before sysvid_nabu_init(): the message
 * uses plain Graphics II mode and its own small font, since the game's
 * font is in RICK.DAT. */
void sys_nabu_checkFiles(void);

#if DEBUG_LOAD_FILENAMES
void sys_nabu_debugPrint(const char *msg, U8 len);
/* Prints `value` as 3 zero-padded decimal digits (000-999 -- every real
 * sprite number fits, SPRITES_NBR_SPRITES is 0xD5/213) via
 * sys_nabu_debugPrint() above. Added on request ("update the debug
 * print to show the sprite requested"): engine/ecm_cache.c's
 * rolling_cache_get() calls this right before a real cache-miss fetch,
 * so the IA console shows which sprite number triggered each load, not
 * just which file/offset -- much easier to match against
 * sprite_index_map[] (engine/sprites.c) than decoding the physical
 * slot a bare filename+offset implies. */
void sys_nabu_debugPrintU16(U16 value);
#endif

#endif /* _SYS_NABU_LOAD_H */
