"""Packs the game's asset files into two RetroNET files, RICK.DAT and
RICK.SPR (uppercase: nabu.ca uppercases uploads), and generates
src/engine/include/res.h with their offsets.

  RICK.DAT -- every non-sprite asset (title, fonts, music, sound effects, map data,
        tile sets, intro text, PCM, stock-VDP sprites). Each entry starts on
        a 4-byte boundary so the game can address it with a 16-bit
        "resource offset" (byte offset >> 2, up to 256KB): RES_xx constants.
        Numbered groups (per map, per intro, per enemy sound) are laid out
        at a fixed stride, so the game computes BASE + index * STRIDE instead
        of building a filename.
  RICK.SPR -- the five interleaved ECM sprite pages (ECMSPR0-4.DAT) back to back. A frame's
        byte offset is its physical slot * 384 (48 frames per page), so it
        needs no table at all.

Source files: assets/ (the original individual RetroNET files).
Run by build.ps1 before every compile; output goes to the RetroNET store.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets"
STORE = Path(sys.argv[1] if len(sys.argv) > 1 else r"c:\nabu\store\cpm\n\1")
HEADER = ROOT / "src" / "engine" / "include" / "res.h"

ALIGN = 4
SHIFT = 2

# Single assets: (file, what it is). Loaded by fixed RES_<file stem>.
SINGLES = [
    ("SF18PAT.DAT", "F18A title pattern"), ("SF18COL.DAT", "F18A title colour"),
    ("SPLSHPAT.DAT", "TMS9918A title pattern"), ("SPLSHCOL.DAT", "TMS9918A title colour"),
    ("MUSIC1.DAT", "title music"),
    ("TF18PATA.DAT", "F18A font pattern"), ("TF18COLA.DAT", "F18A font colour"),
    ("TILECOLA.DAT", "TMS9918A font colour"), ("TILEPATA.DAT", "TMS9918A font pattern"),
    ("SPR0.DAT", "TMS9918A page-0 sprites"),
    ("MAPEFLG.DAT", "map_eflg_c"), ("ENTDATA.DAT", "ent_entdata"),
    ("SPRSEQ.DAT", "ent_sprseq"), ("MVSTEP.DAT", "ent_mvstep"),
    ("JUMP.DAT", "sfx"), ("BULLET.DAT", "sfx"), ("EXPLODE.DAT", "sfx"),
    ("WALK.DAT", "WALK/CRAWL sfx"), ("STICK.DAT", "sfx"), ("BOX.DAT", "sfx"),
    ("SBONUS.DAT", "sfx"), ("PAD.DAT", "sfx"), ("TREASURE.DAT", "sfx"),
    ("DIE.DAT", "sfx"), ("SBONUS2.DAT", "sfx"), ("GAMEOVER.DAT", "sfx"),
    ("BOMBSHHT.DAT", "fuse sfx"),
    ("WAAAAA.PCM", "cheat-key PCM"),
    ("HAFPAT.DAT", "hall of fame banner pattern"), ("HAFCOL.DAT", "hall of fame banner colour"),
]

# Numbered groups: (file pattern, RES id, first, count, what it is). Member
# i is pattern.format(first + i), at RES_<id>_BASE + i * RES_<id>_STRIDE.
GROUPS = [
    ("MAPSUB{}.DAT", "MAPSUB", 1, 4, "per-map submaps"),
    ("MAPCONN{}.DAT", "MAPCONN", 1, 4, "per-map connections"),
    ("MAPBNUM{}.DAT", "MAPBNUM", 1, 4, "per-map block numbers"),
    ("MAPMARK{}.DAT", "MAPMARK", 1, 4, "per-map marks"),
    ("MAPBLK{}.DAT", "MAPBLK", 1, 4, "per-map blocks"),
    ("SPXNUM{}.DAT", "SPXNUM", 1, 4, "per-map extra sprite numbers"),
    ("TF18SP{}.DAT", "TF18SP", 1, 4, "per-map F18A tile set"),
    ("TILESP{}.DAT", "TILESP", 1, 4, "per-map TMS9918A tile set"),
    ("SPXPAT{}.DAT", "SPXPAT", 1, 4, "per-map TMS9918A extra sprites"),
    ("MAPTIT{}.DAT", "MAPTIT", 1, 5, "per-intro title text"),
    ("MAPBOD{}.DAT", "MAPBOD", 1, 5, "per-intro body text"),
    ("INTRMUS{}.DAT", "INTRMUS", 1, 5, "per-intro music"),
    ("ENT{}.DAT", "ENT", 0, 9, "per-enemy-type kill sfx"),
]

# ECM sprite pages, all 3 colour planes interleaved per frame
# (made by tools/interleave_ecm_planes.py).
SPRITE_PAGES = [f"ECMSPR{p}.DAT" for p in range(5)]


def align(n):
    return (n + ALIGN - 1) // ALIGN * ALIGN


def main():
    out = bytearray()
    lines = [
        "/* Generated by tools/pack_assets.py -- do not edit. Offsets into the",
        " * packed RetroNET file RICK.DAT in 4-byte units: load with",
        " * sys_nabu_loadRes(RES_xx, dest, size), byte offset = RES_xx << 2.",
        " * RICK.SPR (ECM sprite pages) needs no table: byte offset = slot * 384. */",
        "#ifndef _RES_H",
        "#define _RES_H",
        "",
    ]

    def place(data):
        nonlocal out
        out += b"\0" * (align(len(out)) - len(out))
        at = len(out)
        out += data
        return at

    for name, what in SINGLES:
        at = place((SRC / name).read_bytes())
        rid = name.split(".")[0]
        lines.append(f"#define RES_{rid:<14} 0x{at >> SHIFT:04X}  /* {name}: {what} */")
    lines.append("")

    for pattern, rid, first, count, what in GROUPS:
        members = [(SRC / pattern.format(first + i)).read_bytes() for i in range(count)]
        stride = align(max(len(m) for m in members))
        base = place(b"")
        for m in members:
            out += m + b"\0" * (stride - len(m))
        files = f"{pattern.format(first)}..{pattern.format(first + count - 1)}"
        lines.append(f"#define RES_{rid}_BASE    0x{base >> SHIFT:04X}  /* {files}: {what} */")
        lines.append(f"#define RES_{rid}_STRIDE  0x{stride >> SHIFT:04X}")
    place(b"")  # pad to a whole 4-byte unit

    if len(out) >> SHIFT > 0xFFFF:
        sys.exit(f"RICK.DAT is {len(out)} bytes -- too big for 16-bit offsets at {ALIGN}-byte alignment")

    sprites = b"".join((SRC / p).read_bytes() for p in SPRITE_PAGES)

    # Where each file's last 4 bytes are: the boot check (main.c) reads them
    # to tell a missing or out-of-date (shorter) file.
    lines.append("")
    lines.append(f"#define RES_DAT_LAST       0x{(len(out) >> SHIFT) - 1:04X}  /* RICK.DAT's last 4 bytes */")
    lines.append(f"#define RES_SPR_LAST       0x{(len(sprites) >> SHIFT) - 1:04X}  /* RICK.SPR's last 4 bytes */")
    lines += ["", "#endif", ""]

    HEADER.write_text("\n".join(lines))
    (STORE / "RICK.DAT").write_bytes(out)
    (STORE / "RICK.SPR").write_bytes(sprites)
    print(f"packed RICK.DAT ({len(out)} bytes) and RICK.SPR ({len(sprites)} bytes) into {STORE}")


main()
